### ISSUE TITLE
Can I use your VI-SVC and ViSinger(VI-SVS) as the backbone of my project and can I credit you in the credits and references?

### ISSUE THREAD

**Issue by NLPV2011** [PlayVoice/VI-SVS#13]
Can I use your VI-SVC and ViSinger(VI-SVS) as the backbone of my project and can I credit you in the credits and references?

**Comment by MaxMax2016** [comment]
yes, you can

**Comment by NLPV2011** [comment]
> yes, you can

Thanks you so much
