### ISSUE TITLE
清华大学深圳研究生院VISinger复现效果

### ISSUE THREAD

**Issue by MaxMax2016** [PlayVoice/VI-SVS#5]
https://thuhcsi.github.io/interspeech2022-expressive-svs/
![QHVISingermodel](https://user-images.githubusercontent.com/16432329/172978139-24fcbac6-b765-467e-9512-e024def64d76.jpg)
![QHVISinger1](https://user-images.githubusercontent.com/16432329/172978197-63130af8-065b-417f-be8f-0e4d0ceccb65.png)

**Comment by yingfenging** [comment]
这篇文章发出来了吗？我没搜到呢
